query photoCount{
  totalPhotos
  allPhotos {
    id
    name
    url
    description
  }
}

mutation newPhoto($input: PostPhotoInput!) {
  postPhoto(input: $input){
    id
    name
    category
    description
  }
}

query photos {
  allPhotos {
    name
    url
    postedBy {
      name
    }
  }
}

query listPhotos {
  allPhotos {
    url
    taggedUsers {
      name

    }
  }
}

# $input Variable for newPhoto mutation
# {
#   "input": {
#     "githubLogin": "gPlake",
#     "name": "Child photo",
#     "category": "LANDSCAPE",
#     "description": "A photo of my cute child"
#   }
# }

# HTTP HEADER for newPhoto mutation
#
# {
#  "Authorization": "<authorization-key>"  
#  }
#

#
# // Subscription Operation Sample
#  subscription {
#    newPhoto {
#      url
#      category
#      postedBy {
#        githubLogin
#        avater
#      }
#    }
#  }
